parent:
  title: "Clinical AI Platform VNEXT (Copy)"
  body: "Roadmap structure copy for Clinical AI Platform VNEXT."
  labels: ["M42", "Oryx"]
  children:
    - title: "Clinical AI Platform VNEXT (Co-Ideation)"
      body: "Sub-issue for Co-Ideation activities."
      children:
        - title: "Solution GTM & Tech Owners Identified & Engaged"
          body: ""
        - title: "Leadership Sponsor Identified"
          body: ""
        - title: "V-team Including SME Identified & Engaged"
          body: ""
        - title: "Customer 0,1 has Verified Need"
          body: ""
        - title: "Affiliate Dedicated Resources for Co-Dev"
          body: ""
        - title: "Customer Personas, Pain Points and Sol Value Prop"
          body: ""
        - title: "Market Sizing and Growth"
          body: ""
        - title: "Scalability Potential and Pipeline"
          body: ""
        - title: "Pricing Strategy Identified"
          body: ""
        - title: "Rev & ACR Expectations"
          body: ""
        - title: "Ref Architecture, Solution V1 Scope"
          body: ""
        - title: "Release Plan Defined"
          body: ""
        - title: "Stage 0 GSF Assets"
          body: ""
    - title: "Clinical AI Platform (Co-Development)"
      body: "Sub-issue for Co-Development activities."
      children:
        - title: "Responsible AI Assessment Started"
          body: ""
        - title: "Customer Environment for Development"
          body: ""
        - title: "Customer Product Owner Assigned"
          body: ""
        - title: "Cloud Adoption Maturity Assessment"
          body: ""
        - title: "Progress Against Release Plan"
          body: ""
        - title: "Repo Contribution Between ISE and the Affiliates"
          body: ""
        - title: "Responsible AI Assessment Completed"
          body: ""
        - title: "Engineering Fundamentals Checklist Completed"
          body: ""
        - title: "Deploying to Customer Environment"
          body: ""
        - title: "Cloud Adoption Maturity Progress"
          body: ""
    - title: "Clinical AI Platform (Co-Selling)"
      body: "Sub-issue for Co-Selling activities."
      children:
        - title: "Partner Center Logistics"
          body: ""
        - title: "Marketplace Readiness"
          body: ""
        - title: "Co-Sell Collateral"
          body: ""
        - title: "Reference Customers"
          body: ""
        - title: "Seller Incentives"
          body: ""
        - title: "Seller Enablement"
          body: ""
        - title: "Integration with MCEM"
          body: ""
        - title: "Support Readiness"
          body: ""
        - title: "Telemetry and Response"
          body: ""
