name: Auto-Create Standard Sub-Issues for Co-ideation Group

on:
  issues:
    types: [opened, labeled]

jobs:
  create-sub-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create Standard Sub-Issues for Co-ideation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const parentIssueNumber = context.payload.issue.number;

            // Get parent issue info
            const parentIssue = await github.rest.issues.get({
              owner,
              repo,
              issue_number: parentIssueNumber
            });

            // Check if parent issue has "Co-ideation" label
            const parentLabels = parentIssue.data.labels.map(label => label.name);
            if (!parentLabels.includes("Co-ideation")) {
              console.log("Issue does not have 'Co-ideation' label. Skipping sub-issue creation.");
              return;
            }

            const parentAssignees = parentIssue.data.assignees.map(user => user.login);

            // Sub-issue titles
            const sub
