name: Auto-Create Standard Sub-Issues

on:
  issues:
    types: [opened]

jobs:
  create-sub-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create Standard Sub-Issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const parentIssueNumber = context.payload.issue.number;

            // Get parent issue info
            const parentIssue = await github.rest.issues.get({
              owner,
              repo,
              issue_number: parentIssueNumber
            });

            const parentLabels = parentIssue.data.labels.map(label => label.name);
            const parentAssignees = parentIssue.data.assignees.map(user => user.login);

            const subIssueTitles = [
              "Solution GTM & Tech Owners Identified & Engaged",
              "Leadership Sponsor Identified",
              "V-team Including SME Identified & Engaged",
              "Customer 0,1 has Verified Need",
              "Customer Personas, Pain Points and Sol Value Prop",
              "Market Sizing and Growth",
              "Scalability Potential and Pipeline",
              "Pricing Strategy Identified",
              "Rev & ACR Expectations",
              "Stage 0 GSF Assets",
              "Ref Architecture, Solution V1 Scope",
              "Release Plan Defined",
              "Affiliate Dedicated Resources for Co-Dev"
            ];

            async function run() {
              for (const title of subIssueTitles) {
                try {
                  const subIssue = await github.rest.issues.create({
                    owner,
                    repo,
                    title,
                    body: `Automatically created sub-issue. Parent: #${parentIssueNumber}`,
                    labels: parentLabels,
                    assignees: parentAssignees
                  });
                  console.log(`Created sub-issue: ${title} - #${subIssue.data.number}`);
                  await new Promise(resolve => setTimeout(resolve, 15000)); // 15s delay
                } catch (error) {
                  console.log(`Error creating "${title}":`, error.message);
                  if (error.message && error.message.includes('rate limit')) {
                    console.log("Rate limit reached. Pausing for 1 minute...");
                    await new Promise(resolve => setTimeout(resolve, 60000)); // Wait 1 minute, then continue
                  }
                }
              }
            }

            run();
